### ISSUE TITLE
Script fails with IsoPath set to a relative path

### ISSUE THREAD

**Issue by MikaelSmith** [jangelfdez/DeployNanoServer#7]
```
C:\Users\lasth\Nano\DeployNanoServer.ps1 : You cannot call a method on a null-valued expression.
At line:1 char:1
+ .\DeployNanoServer.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [DeployNanoServer.ps1], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,DeployNanoServer.ps1
```

Occurs because $IsoPath.AbsolutePath returns null for something like ".\path_to_image.iso".

**Comment by jangelfdez** [comment]
Thanks Mikael, I think the bug is now corrected. By the way, you can check the oficial script of the Nano team published some days ago: http://blogs.technet.com/b/nanoserver/archive/2015/06/16/powershell-script-to-build-your-nano-server-image.aspx
